services:
  app:
    build: .
    ports:
      - "4444:4444"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    # Healthcheck (optional)
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4444"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
